spring:

  devtools:
    livereload:
      port: 35730

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:8081"
      client:
        registration:
          #datos del método -> registeredClientRepository
          app-client:
            provider: spring
            client-id: app-client
            client-secret: password-client
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope:
              - openid
              - profile
              - read
            client-name: app-client
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:8081"